# Generated by Django 2.2.10 on 2020-04-19 21:47

from django.db import migrations, models
import todo.utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200420_0257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='motivation',
            field=models.ImageField(blank=True, null=True, upload_to='motivation-pictures', validators=[todo.utils.validators.validate_file_size, todo.utils.validators.validate_extension]),
        ),
    ]
